### ISSUE TITLE
[RAML 0.8] Method's don't have 'displayName'

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-definition-system#48]
`HasNormalParameters` -> `MethodBase` -> `Method`

**Comment by KonstantinSviridov** [comment]
It appears that in RAML 0.8 method does have `displayName`, according to old js parser tests:
https://github.com/mulesoft-labs/raml-parsers-functional-tests/blob/master/test/specs/parser.js#L6713

**Comment by sichvoge** [comment]
No it does not, that was added accidentally; the spec usually is the source of truth and there was never a `displayName` https://github.com/raml-org/raml-spec/blob/master/raml-0.8.md#methods

**Comment by KonstantinSviridov** [comment]
@sichvoge Removing `displayName` from RAML 0.8 Method will introduce incompatibility with the old JS parser. A minor one, but anyway. Do we really want to move this way?

**Comment by sichvoge** [comment]
Yes, since we need to comply against the spec which says that a method does not have a `displayName`.

**Comment by KonstantinSviridov** [comment]
ok
