### ISSUE TITLE
Rename HasNormalParameters

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-definition-system#49]
Can we rename that class; it does not really say anything. What are normal parameters etc. What about just saying `HasParameters`?

**Comment by KonstantinSviridov** [comment]
By "normal parameters " we actually mean headers nad query parameters which are parameters of HTTP call. May be `HasHttpParameters` is ok?

**Comment by sichvoge** [comment]
you also have a bit more in there like `displayName`; not sure if that should be part of that. And also it should not extend from RAMLLanguageElement in this case right?

**Comment by KonstantinSviridov** [comment]
Yes, that's right.
