### ISSUE TITLE
[RAML 0.8] SecuritySchemePart should not extend from MethodBase

### ISSUE THREAD

**Issue by sichvoge** [raml-org/raml-definition-system#51]
As far as I can see; `describedBy` (which is a SecuritySchemePart) should only have the following:
- headers
- queryParameters
- responses

**Comment by KonstantinSviridov** [comment]
I would also keep `body`.

**Comment by sichvoge** [comment]
The spec is quite vague about that tbh. The old parser did not support `body` inside `describedBy` as far as I can tell. Let me double check.

**Comment by sichvoge** [comment]
OK double checked that; it seems that 0.8 spec states the following:

> The describedBy attribute MAY be used to apply a trait-like structure

And it seems what ever I put into describedBy that is also available in a trait declaration it works with the old parser. Out of fine I created a security scheme that has all the different possibilities that a trait has in it:

``` yaml
securitySchemes:
  - test:
      type: x-{other}
      description: API Key only
      describedBy:
        displayName: hghgh
        baseUriParameters:
        headers:
        queryParameters:
        responses:
        securedBy: []
        body:
        description:
        usage: # only that fails
        protocols: []
```

The parser fails only on `usage`, the rest seems to be supported. I'll double check with the java team.
